apiVersion: v1
kind: Service
metadata:
  name: estock-config-server
  labels:
    app: estock-config-server
spec:
  clusterIP: None
  ports:
    - port: 8888
      name: estock-config-server
  selector:
    app: estock-config-server

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: estock-config-server
spec:
  serviceName: "estock-config-server"
  replicas: 1
  selector:
    matchLabels:
      app: estock-config-server
  template:
    metadata:
      labels:
        app: estock-config-server
    spec:
      containers:
        - name: estock-config-server
          image: suriyasiva8/estock-config-server
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
---                  

apiVersion: v1
kind: Service
metadata:
  name: estock-config-server-lb
  labels:
    app: estock-config-server
spec:
  selector:
    app: estock-config-server
  type: NodePort
  ports:
    - port: 80
      targetPort: 8888