apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
stringData:
  uri: mongodb://estock-mongo:orpvCk89DFZmc6sZJ7j3gdvZTtTdaSypYhvLdvmpGlJyY1KP3QbshuhS5G2Wb2xbkPvMCdP5cNe5nkEKbuccGg==@estock-mongo.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@estock-mongo@
