apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
stringData:
  uri: mongodb://estock-mongo:LbaTs8Gziqq92LoTAxQA7eDUxB3rgx48oDblL2eN6d8sqFlQgsTBasPdZNCgwcCSTwmJCOpr5OHFLj0CoNF0HA==@estock-mongo.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@estock-mongo@ 
